Add wagtail aa1
snek-at/wagtail-template pull request #10
Opened 2020-07-30 14:11 UTC by kleberbaum

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
-  Currently there is no easy option to edit pages. #1 
-  Currently the default user model is used. #2 
-  Currently the default image model is used. #3 
-  Currently the default image model is used. #4
-  Currently there is no app with  
-  Currently there is no easy option to edit pages.
-  Currently there is no easy option to edit pages.

**What is the new behavior (if this is a feature change)?**
- 

**Other information**:
-

2020-07-30 14:44 UTC, schettn requested changes
- We have to migrate to our new licence tag.
- Also the code doesn't comply with [Black](https://github.com/psf/black) standard.

2020-07-31 09:29 UTC, kleberbaum reviewed
Should be ok to merge.

2020-07-31 09:34 UTC, pinterid commented on esite/core/apps.py
>  # Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:35 UTC, pinterid commented on esite/documents/models.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast.

2020-07-31 09:35 UTC, pinterid commented on esite/home/apps.py
>  # Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:37 UTC, pinterid commented on esite/images/models.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:37 UTC, pinterid commented on esite/navigation/models.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:38 UTC, pinterid commented on esite/navigation/templatetags/navigation_tags.py
> +"""
```suggestion
```

2020-07-31 09:38 UTC, pinterid commented on esite/navigation/templatetags/navigation_tags.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:39 UTC, pinterid commented on esite/settings/base.py
> +# > Template Configuration
?

2020-07-31 09:40 UTC, pinterid commented on esite/settings/base.py
>  # Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:40 UTC, pinterid commented on esite/settings/development.py
>  # Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:40 UTC, pinterid commented on esite/settings/production.py
>  # Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:41 UTC, pinterid commented on esite/urls.py
>  # Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:41 UTC, pinterid commented on esite/user/admin.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:41 UTC, pinterid commented on esite/user/apps.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:42 UTC, pinterid commented on esite/user/blocks.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:42 UTC, pinterid commented on esite/user/models.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:42 UTC, pinterid commented on esite/user/schema.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:43 UTC, pinterid commented on esite/user/tests.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:43 UTC, pinterid commented on esite/user/views.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:43 UTC, pinterid commented on esite/user/wagtail_hooks.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:43 UTC, pinterid commented on esite/user/widgets.py
> +# Copyright © 2019 Werbeagentur Christian Aichner
Change to Simon Prast

2020-07-31 09:45 UTC, pinterid commented on esite/utils/wagtail_hooks.py
> +"""
```suggestion
```

2020-07-31 09:45 UTC, pinterid requested changes
A few changes should be made

2020-07-31 09:54 UTC, kleberbaum reviewed
Should be ok to merge now.

2020-07-31 09:54 UTC, kleberbaum commented on esite/settings/base.py
The env variable has to be assigned in the base settings.
```suggestion
env = os.environ.copy()

```

2020-07-31 11:44 UTC, schettn approved these changes
LGTM! :)

2020-07-31 11:49 UTC, pinterid approved these changes
Looks ok to merge.

2020-07-31 11:50 UTC, merged