Add bifrost aa1
snek-at/wagtail-template pull request #12
Opened 2020-07-31 12:46 UTC by kleberbaum

**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [ ] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently there is no self generating GraphQL API like wagtail-grapple. #11 

**What is the new behavior (if this is a feature change)?**
- Currently there is a self generating GraphQL API like wagtail-grapple. Closes #11 

**Other information**:
- Ref: https://pypi.org/project/graphql-core/
- Ref: https://pypi.org/project/graphene-django/
- Ref: https://pypi.org/project/graphene-django-optimizer/
- Ref: https://pypi.org/project/django-graphql-jwt/
- Ref: https://pypi.org/project/channels/
- Ref: https://pypi.org/project/asgi_redis/
- Ref: https://pypi.org/project/graphql-ws/

2020-07-31 12:58 UTC, pinterid commented on esite/urls.py
> +    url(r"", include(api_urls)),
Is "r" required?
```suggestion
    url("", include(api_urls)),
```

2020-07-31 12:59 UTC, pinterid requested changes
Just found a single thing

2020-07-31 13:01 UTC, Aichnerc approved these changes
Only looked at comments and general look and feel. I'm no python dev to judge any functionality or coding style. LGTM.

2020-07-31 21:21 UTC, schettn approved these changes
LGTM

2020-08-02 14:21 UTC, pinterid approved these changes
LGTM

2020-08-03 09:59 UTC, pinterid approved these changes
LGTM

2020-08-03 10:49 UTC, simonprast approved these changes
looks very good to me

2020-08-03 11:23 UTC, schettn approved these changes
lgtm

2020-08-03 11:49 UTC, merged

2020-08-03 11:55 UTC, kleberbaum reviewed
Was totally ok to merge.